#!/bin/sh
ed -s asio.h <<< $'g/unsigned long/s//ULONG/g\nw\nq'
ed -s asio.h <<< $'g/long long int/s//LONGLONG/g\nw\nq'
ed -s asio.h <<< $'g/long int/s//LONG/g\nw\nq'
ed -s asio.h <<< $'g/long/s//LONG/g\nw\nq'
ed -s asio.h <<< $'g/(\*bufferSwitch)/s//(CALLBACK *bufferSwitch)/g\nw\nq'
ed -s asio.h <<< $'g/(\*sampleRateDidChange)/s//(CALLBACK *sampleRateDidChange)/g\nw\nq'
ed -s asio.h <<< $'g/(\*asioMessage)/s//(CALLBACK *asioMessage)/g\nw\nq'
ed -s asio.h <<< $'g/(\*bufferSwitchTimeInfo)/s//(CALLBACK *bufferSwitchTimeInfo)/g\nw\nq'
